---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Safe Spot for kids - Personal check in"
keywords:    "safe, web, for, kids, control, content, restricted, filter, porn, nofap, blocker, child, limited, adult, access, best, app, mums, ios, whitelist"
description: "Safe Web is a web browser for iPhone and iPad devices. Don't worry about what your children browse as they will only see what you let them see. Safe Web is a whitelist based Internet browser that only allows to navigate to some predefined websites or domains of your choose. Apart from that, Safe Web creates a sandbox environment where the user can't leave the bookmarked websites domains."
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-25289053-8 ## put YOUR key here to enable tracking! (blank to disable)
appstore_link: "https://itunes.apple.com/app/safe-spot-personal-check-in/id697940443?ct=web&mt=8&at=1000lom5"

url: https://safespot.bobgoo.com
enforce_ssl: safespot.bobgoo.com

### template colors, used site-wide via css ###
colors:
  red:       '#8E2223'      
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#1B6C25'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gtgold:    '#E0A01F'
  gtnavy:    '#01192F'
  gtmetallic: '#A08452'

kramdown:
  auto_ids:  false

gems:
  - jekyll-seo-tag