---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Safe Spot for kids - Location check in for family protection"
keywords:    "teen, children, control, supervised, monitoring, away, hang, out, where, teenager, wife, parents, cheat, cheating, spare, time, adultery, audit, child, situation, place, position, checkin, register, mum, dad, monitor, nanny, sign"
description: "Safe Spot is a personal check in app for kids. Safe Spot lets your children check in and send a message once they arrive to any of the safe locations bookmarked by you. This way you will always be sure that they are where they are supposed to be. "
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-25289053-8 ## put YOUR key here to enable tracking! (blank to disable)
appstore_link: "https://itunes.apple.com/app/safe-spot-personal-check-in/id697940443?ct=web&mt=8&at=1000lom5"

url: https://safespot.bobgoo.com
enforce_ssl: safespot.bobgoo.com

twitter:
    username: "@SafeSpotApp"
    
defaults:
  -
    scope:
        path: ""
    values:
        image:
            #path: /img/Icon-Rounded-256.png
            twitter: /img/FBBanner.png
            facebook: /img/FBBanner.png
            height: 630
            width: 1200    

### template colors, used site-wide via css ###
colors:
  red:       '#8E2223'      
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#1B6C25'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gtgold:    '#E0A01F'
  gtnavy:    '#01192F'
  gtmetallic: '#A08452'

kramdown:
  auto_ids:  false

gems:
  - jekyll-seo-tag